name: c_scheme_gen
description: Getters and setters to save variables to and from Map
version: 1.0.21
publish_to: https://pub.dev/

repository: https://github.com/edunnett/c_scheme_gen
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^5.12.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner: 2.4.5
