name: c_scheme_gen
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: https://pub.dev/

repository: https://github.com/edunnett/c_scheme_gen
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  build: ^2.1.1  
  source_gen: ^1.0.0  
  analyzer: ^1.0.0


dev_dependencies:
  build_test: ^2.1.2
  build_runner: ^2.1.2